### ISSUE TITLE
windows Install Error

### ISSUE THREAD

**Issue by Qipccc** [strawlab/python-pcl#163] opened 2018-02-07 08:44 UTC
I have installed PCL 18.1 and gtk+，but when I excute "python setup.py build_ext -i" it has error :

LINK : fatal error LNK1104: cannot open file 'libboost_date_time-vc140-mt-1_64.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1104

**Comment by ymwtz** [comment] 2018-03-05 13:02
I guess you used wrong PCL installer.
I used PCL-1.8.1-AllInOne-msvc2017-win64.exe to install PCL, and I find the libboost version is  vc141. So I used PCL-1.8.1-AllInOne-msvc2015-win64.exe.

**Comment by Qipccc** [comment] 2018-05-23 04:33
when i re-install it, it was solved.i don't know what's wrong before

**Comment by niranjanreddy891** [comment] 2018-05-23 05:17
Ok. Close the issue if the issue is solved. :)

**Closed** 2018-05-23 07:27 UTC

**Comment by scizors** [comment] 2019-05-27 08:33
ya thanks for this
